# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

   # VM name
   config.vm.box = "ubuntu/trusty64"

   # Enable ssh
   config.ssh.forward_agent = true

   # Provider-specific configuration
   config.vm.provider "virtualbox" do |v|
      v.name = "Aikau Testing VM"
      v.memory = 8192
      v.cpus = 4
      v.customize ["modifyvm", :id, "--vram", "128"]
   end

   # Configure the VM on its own private_network with IP 192.168.56.4
   # The host machine will be assigned a new network connection on 192.168.56.1
   config.vm.network "private_network", ip: "192.168.56.4"

   # Run the setup.sh file to provision this VM
   config.vm.provision :shell, :path => "setup.sh"

end
